### ISSUE TITLE
请问base_model_name不是生成的权重文件名字吗？

### ISSUE THREAD

**Issue by xin94wang** [liutongkun/EdgRec#3]
![image](https://github.com/user-attachments/assets/d3371182-6ffb-4cbe-8709-c003d30cc30e)

我准备在自己电脑上test训练出来的权重文件，可是提示FileNotFoundError: [Errno 2] No such file or directory: './EdgRec_0.0001_20_bs4_bottle_.pckl_screw_.pckl'

请问是我设置的这个base_model_name错误了吗？

**Comment by xin94wang** [comment]
问题已解决，打扰您了

**Comment by liutongkun** [comment]
好的。EdgRec是原始未改进工作，改进版可以看FAIR那个仓库



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xin94wang ***@***.***&gt;
发送时间: 2024年12月25日 12:54
收件人: liutongkun/EdgRec ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liutongkun/EdgRec] 请问base_model_name不是生成的权重文件名字吗？ (Issue #3)





 
问题已解决，打扰您了
